---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: tanzu-packages-namespaces
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 1m0s
  path: ./namespaces
  prune: true
  sourceRef:
    kind: GitRepository
    name: tmc-cd-wordpress-demo
    namespace: tanzu-continuousdelivery-resources
