apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tanzu-continuousdelivery-resources
resources:
  - repository.yaml
  - release.yaml
configMapGenerator:
  - name: wordpress-values
    files:
      - values.yaml=my-values.yaml
configurations:
  - kustomizeconfig.yaml
