apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: wordpress
  namespace: blog
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/wordpress
      version: '22.1.3'
      sourceRef:
        kind: GitRepository
        name: tmc-cd-wordpress-demo 
        namespace: default
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: wordpress-values
