apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: wordpress
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 1m
  url: https://github.com/christschn81/tmc-cd-wordpress-demo
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
